use dashmap::DashMap;
use snip36_core::config::Config;
use snip36_core::rpc::StarknetRpc;
use snip36_core::types::Session;
use tokio::sync::Mutex;
use uuid::Uuid;

/// Validate and canonicalize a session identifier before it is used in a file
/// name. Sessions are UUIDs generated by the playground, so accepting any
/// other form would only allow path-like data to reach proof artifact paths.
pub fn canonical_session_id(session_id: &str) -> Result<String, String> {
    Uuid::parse_str(session_id)
        .map(|id| id.hyphenated().to_string())
        .map_err(|_| "session_id must be a UUID".to_string())
}

/// Shared application state for generic SNIP-36 routes.
///
/// Application-specific state (e.g. CoinFlip deployments) lives in app crates
/// and is composed at the binary level (see `apps/playground`).
pub struct AppState {
    pub config: Config,
    pub rpc: StarknetRpc,
    pub sessions: DashMap<String, Session>,
    /// Mutex to serialize sncast invocations that share the master account nonce.
    pub sncast_lock: Mutex<()>,
}

impl AppState {
    pub fn new(config: Config) -> Self {
        let rpc = StarknetRpc::new(&config.rpc_url);
        Self {
            config,
            rpc,
            sessions: DashMap::new(),
            sncast_lock: Mutex::new(()),
        }
    }

    /// Get or create a session for the given ID (returns a clone for reading).
    pub fn get_session(&self, session_id: &str) -> Session {
        self.sessions
            .entry(session_id.to_string())
            .or_default()
            .clone()
    }

    /// Atomically mutate a session, avoiding lost-update races from clone + write-back.
    pub fn update_session_with(&self, session_id: &str, f: impl FnOnce(&mut Session)) {
        let mut entry = self.sessions.entry(session_id.to_string()).or_default();
        f(entry.value_mut());
    }
}

#[cfg(test)]
mod tests {
    use super::canonical_session_id;

    #[test]
    fn canonical_session_id_rejects_path_like_values() {
        assert_eq!(
            canonical_session_id("9d5e8f21-f7e3-4ad4-9f0a-695991551ead").as_deref(),
            Ok("9d5e8f21-f7e3-4ad4-9f0a-695991551ead")
        );
        assert_eq!(
            canonical_session_id("9d5e8f21f7e34ad49f0a695991551ead").as_deref(),
            Ok("9d5e8f21-f7e3-4ad4-9f0a-695991551ead")
        );
        assert!(canonical_session_id("../../output").is_err());
    }
}
